<?php


namespace app\api\controller;


use app\common\lib\Key;
use app\common\lib\Show;

class AuthBase extends ApiBase
{
    public $token = '';
    public $userId = 0;
    public $username = '';

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->token = $this->request->header("authorization");
//        return  $this->show(1,'null',$this->request->header('authorization'));
        if(!$this->token || !$this->isLogin()) {
            return $this->show(config("status.user_not_login"), "登录失败", null);
        }
    }

    public function isLogin()
    {
        $tokenInfo = cache(Key::token($this->token));
        if(empty($tokenInfo) || empty($tokenInfo['id']) || empty($tokenInfo['username'])) {
            return false;
        }

        $this->userId = $tokenInfo['id'];
        $this->username = $tokenInfo['username'];
        return true;
    }
}